site_name: Triton AI Docs 
nav:
  - Home: index.md
  - 'Everything Jetson':
    - 'Jetson Setup': jetson_setup.md
    - 'Jetson Docker': jetson_docker.md
  - 'Tools':
    - 'Vim': vim_intro.md
    - 'Tmux': tmux_intro.md

theme: readthedocs
